/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package disquera.gui;

import java.security.Principal;

/**
 *
 * @author Sebastian Cornejo
 */
public class FramePrincipal extends javax.swing.JFrame {
    
    private javax.swing.ImageIcon imagenFondoOriginal;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FramePrincipal.class.getName());

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() 
    {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null); 
        String rutaImagen = "/disquera/imagenes/foto.png";
        java.net.URL url = getClass().getResource(rutaImagen);
        
        if (url != null) 
        {
            try 
            {
               
                javax.swing.ImageIcon imagenOriginal = new javax.swing.ImageIcon(url);
                
                
                int anchoVentana = this.getWidth();
                int altoVentana = this.getHeight();
                
               
                java.awt.Image imagenEscalada = imagenOriginal.getImage().getScaledInstance(anchoVentana, altoVentana, java.awt.Image.SCALE_SMOOTH);
                
                
                lblFondo.setIcon(new javax.swing.ImageIcon(imagenEscalada));
                lblFondo.setSize(anchoVentana, altoVentana);
                lblFondo.setLocation(0, 0);
                
            } catch (Exception e) 
            {
                System.out.println("Error al ajustar imagen: " + e.getMessage());
            }
        }
        else 
        {
            System.out.println("No se encontró la imagen de fondo.");
        }
        
    }
    
    public void setComponents()
    {
        super.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        lblFondo = new javax.swing.JLabel();
        barraDeMenuDisquera = new javax.swing.JMenuBar();
        menuDisquera = new javax.swing.JMenu();
        menuDisco = new javax.swing.JMenu();
        AgregarDisco = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        Listar = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenuItem();
        menuCancion = new javax.swing.JMenu();
        menuAgregarCancion = new javax.swing.JMenuItem();
        menuModificarCancion = new javax.swing.JMenuItem();
        menuEliminarCancion = new javax.swing.JMenuItem();
        menuListarCancion = new javax.swing.JMenuItem();
        menuBuscarCancion = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Disquera V.1.0");
        setBackground(new java.awt.Color(51, 51, 255));

        barraDeMenuDisquera.setName(""); // NOI18N

        menuDisquera.setText("Disquera");

        menuDisco.setText("Disco");

        AgregarDisco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        AgregarDisco.setText("Agregar");
        AgregarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDiscoActionPerformed(evt);
            }
        });
        menuDisco.add(AgregarDisco);

        Modificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        menuDisco.add(Modificar);

        Eliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        menuDisco.add(Eliminar);

        Listar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Listar.setText("Listar");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        menuDisco.add(Listar);

        Buscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        menuDisco.add(Buscar);

        menuDisquera.add(menuDisco);

        menuCancion.setText("Cancion");

        menuAgregarCancion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuAgregarCancion.setText("Agregar");
        menuAgregarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarCancionActionPerformed(evt);
            }
        });
        menuCancion.add(menuAgregarCancion);

        menuModificarCancion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuModificarCancion.setText("Modificar");
        menuModificarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuModificarCancionActionPerformed(evt);
            }
        });
        menuCancion.add(menuModificarCancion);

        menuEliminarCancion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuEliminarCancion.setText("Eliminar");
        menuEliminarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarCancionActionPerformed(evt);
            }
        });
        menuCancion.add(menuEliminarCancion);

        menuListarCancion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuListarCancion.setText("Listar");
        menuListarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarCancionActionPerformed(evt);
            }
        });
        menuCancion.add(menuListarCancion);

        menuBuscarCancion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuBuscarCancion.setText("Buscar");
        menuBuscarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarCancionActionPerformed(evt);
            }
        });
        menuCancion.add(menuBuscarCancion);

        menuDisquera.add(menuCancion);

        barraDeMenuDisquera.add(menuDisquera);

        setJMenuBar(barraDeMenuDisquera);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:AUN NO ESTA CREADOOOOOOO
        FrmActualizarDisco oFrmActualizarDisco = new FrmActualizarDisco(this, true);
        oFrmActualizarDisco.setVisible(true);
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:AUN NO ESTA CREADOOOOOOO
        FrmEliminarDisco oFrmEliminarDisco = new FrmEliminarDisco(this, true);
        oFrmEliminarDisco.setVisible(true);
    }//GEN-LAST:event_EliminarActionPerformed

    private void AgregarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDiscoActionPerformed
        // TODO add your handling code here:AUN NO ESTA CREADOOOOOOO
        FrmIngresoDisco oFrmIngresoDisco = new FrmIngresoDisco(this, true);
        oFrmIngresoDisco.setVisible(true);
    }//GEN-LAST:event_AgregarDiscoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        FrmBuscarDisco oFrmBuscarDisco = new FrmBuscarDisco(this, true);
        oFrmBuscarDisco.setVisible(true);
    }//GEN-LAST:event_BuscarActionPerformed

    private void menuEliminarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarCancionActionPerformed
        // TODO add your handling code here:
        FrmEliminarCancion oFrmEliminarCancion = new FrmEliminarCancion(this, true);
        oFrmEliminarCancion.setVisible(true);
    }//GEN-LAST:event_menuEliminarCancionActionPerformed

    private void menuModificarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuModificarCancionActionPerformed
        // TODO add your handling code here:
        FrmActualizarCancion oFrmActualizarCancion = new FrmActualizarCancion(this, true);
        oFrmActualizarCancion.setVisible(true);
    }//GEN-LAST:event_menuModificarCancionActionPerformed

    private void menuBuscarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarCancionActionPerformed
        // TODO add your handling code here:
        FrmBuscarCancion oFrmBuscarancion = new FrmBuscarCancion(this, true);
        oFrmBuscarancion.setVisible(true);
    }//GEN-LAST:event_menuBuscarCancionActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        // TODO add your handling code here:
        FrmListarDisco oFrmListarDisco = new FrmListarDisco(this, true);
        oFrmListarDisco.setVisible(true);
    }//GEN-LAST:event_ListarActionPerformed

    private void menuAgregarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarCancionActionPerformed
        // TODO add your handling code here:
        FrmIngresoCancion oFrmIngresoCancion = new FrmIngresoCancion(this, true);
        oFrmIngresoCancion.setVisible(true);
        
    }//GEN-LAST:event_menuAgregarCancionActionPerformed

    private void menuListarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarCancionActionPerformed
        // TODO add your handling code here:
        FrmListarCancion oFrmListarCancion = new FrmListarCancion(this, true);
        oFrmListarCancion.setVisible(true);
    }//GEN-LAST:event_menuListarCancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
        // Crear la ventana principal y hacerla visible.
        new FramePrincipal().setVisible(true);
        java.awt.EventQueue.invokeLater(() -> new FramePrincipal().setVisible(true));
    });
       
       }
    
    private void ajustarImagenAlTamaño() {
        if (imagenFondoOriginal != null) {
            
            int anchoVentana = this.getWidth();
            int altoVentana = this.getHeight();
            
            
            if (anchoVentana > 0 && altoVentana > 0) {
                
                
                java.awt.Image imagenEscalada = imagenFondoOriginal.getImage().getScaledInstance(anchoVentana, altoVentana, java.awt.Image.SCALE_SMOOTH);
                
                
                lblFondo.setIcon(new javax.swing.ImageIcon(imagenEscalada));
                
                
                lblFondo.setSize(anchoVentana, altoVentana);
                lblFondo.setLocation(0, 0);
            }
        }
    }
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarDisco;
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Listar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JMenuBar barraDeMenuDisquera;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JMenuItem menuAgregarCancion;
    private javax.swing.JMenuItem menuBuscarCancion;
    private javax.swing.JMenu menuCancion;
    private javax.swing.JMenu menuDisco;
    private javax.swing.JMenu menuDisquera;
    private javax.swing.JMenuItem menuEliminarCancion;
    private javax.swing.JMenuItem menuListarCancion;
    private javax.swing.JMenuItem menuModificarCancion;
    // End of variables declaration//GEN-END:variables
}
