/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package disquera.gui;

import disquera.beans.Cancion;
import disquera.exception.CancionException;
import disquera.datos.CancionDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian
 */
public class FrmActualizarCancion extends javax.swing.JDialog 
{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmActualizarCancion.class.getName());

    /**
     * Creates new form FrmActualizarCancion
     */
    public FrmActualizarCancion(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAcutalizaMusica = new javax.swing.JLabel();
        lblIdCancion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombreCancion = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        botonCancelarCancion = new javax.swing.JButton();
        botonOkCancion = new javax.swing.JButton();
        lblDuracionCancion1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualización de Música");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAcutalizaMusica.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAcutalizaMusica.setForeground(new java.awt.Color(255, 255, 255));
        lblAcutalizaMusica.setText("Actualiza Tu Música");
        getContentPane().add(lblAcutalizaMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 240, 25));

        lblIdCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIdCancion.setForeground(new java.awt.Color(255, 255, 255));
        lblIdCancion.setText("ID");
        getContentPane().add(lblIdCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 48, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 337, -1));

        lblNombreCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreCancion.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCancion.setText("Nombre");
        getContentPane().add(lblNombreCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 60, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 337, -1));

        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });
        txtDuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuracionKeyTyped(evt);
            }
        });
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 337, -1));

        botonCancelarCancion.setBackground(new java.awt.Color(255, 0, 0));
        botonCancelarCancion.setText("Cancelar");
        botonCancelarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarCancionActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 353, -1, 30));

        botonOkCancion.setBackground(new java.awt.Color(51, 204, 0));
        botonOkCancion.setText("OK");
        botonOkCancion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOkCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOkCancionActionPerformed(evt);
            }
        });
        getContentPane().add(botonOkCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 60, 30));

        lblDuracionCancion1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDuracionCancion1.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracionCancion1.setText("Duracion");
        getContentPane().add(lblDuracionCancion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        lblFondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disquera/imagenes/fotodos.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 940, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    private void botonCancelarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarCancionActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_botonCancelarCancionActionPerformed

    private void botonOkCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOkCancionActionPerformed
        // TODO add your handling code here:
        try
        { 
            if (txtId.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty() || txtDuracion.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos", "Error de Registro", JOptionPane.WARNING_MESSAGE);
                return;             
            }       
           
            int Id;
            try 
            {
                Id = Integer.parseInt(txtId.getText().trim());
            }
            catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "El ID debe ser numérico.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            String Nombre = txtNombre.getText().trim();
            
            int Duracion;
            try
            {
                Duracion = Integer.parseInt(txtDuracion.getText().trim());
            }
            catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "La duración debe ser numérica.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            CancionDAO can = new CancionDAO();
            Cancion buscada = can.buscarCancion(Id);
            if (buscada == null)
            {
                JOptionPane.showMessageDialog(this,  "No existe una canción con ese ID.", "No encontrado", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Cancion oCancion = new Cancion(Id, Nombre, Duracion);
            boolean ok = can.actualizarCancion(oCancion);
            
            if(ok)
            {
                JOptionPane.showMessageDialog(this, "Operación realizada con éxito");
            } 
            else 
            {
                JOptionPane.showMessageDialog(this, "No se actualizó ninguna fila");
            }
            
            super.dispose();
        }
         
        catch(CancionException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
        }
        
        catch(NumberFormatException nex)
        {
            JOptionPane.showMessageDialog(this, "Debe Ingresar Los Datos", "Error de Registro", JOptionPane.WARNING_MESSAGE);
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error Inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_botonOkCancionActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        // TODO add your handling code here:
        char caracterTeclado = evt.getKeyChar();
        
        if(!Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char caracterTeclado = evt.getKeyChar();
        
        if(Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDuracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuracionKeyTyped
        // TODO add your handling code here:
        char caracterTeclado = evt.getKeyChar();
        
        if(!Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtDuracionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmActualizarCancion dialog = new FrmActualizarCancion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelarCancion;
    private javax.swing.JButton botonOkCancion;
    private javax.swing.JLabel lblAcutalizaMusica;
    private javax.swing.JLabel lblDuracionCancion1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIdCancion;
    private javax.swing.JLabel lblNombreCancion;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
