/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package disquera.gui;
import disquera.exception.DiscoException;
import disquera.beans.Disco; 
import disquera.datos.DiscoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian
 */
public class FrmActualizarDisco extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmActualizarDisco.class.getName());

    /**
     * Creates new form FrmActualizarDisco
     */
    public FrmActualizarDisco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonActualizarDisco = new javax.swing.JButton();
        botonCerrarActualizarDisco = new javax.swing.JButton();
        lblActualizarDisco = new javax.swing.JLabel();
        lblIDAct = new javax.swing.JLabel();
        lblNombreAct = new javax.swing.JLabel();
        lblArtistaAct = new javax.swing.JLabel();
        lblAnoAct = new javax.swing.JLabel();
        lblDuracionAct = new javax.swing.JLabel();
        lblRankingAct = new javax.swing.JLabel();
        lblGeneroAct = new javax.swing.JLabel();
        txtIdAct = new javax.swing.JTextField();
        txtNombreAct = new javax.swing.JTextField();
        txtArtistaAct = new javax.swing.JTextField();
        txtAnoAct = new javax.swing.JTextField();
        txtDuracionAct = new javax.swing.JTextField();
        txtRankingAct = new javax.swing.JTextField();
        txtGeneroAct = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizacion disco");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonActualizarDisco.setText("Actualizar Disco");
        botonActualizarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarDiscoActionPerformed(evt);
            }
        });
        getContentPane().add(botonActualizarDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, -1, -1));

        botonCerrarActualizarDisco.setText("Cerrar");
        botonCerrarActualizarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActualizarDiscoActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerrarActualizarDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        lblActualizarDisco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblActualizarDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblActualizarDisco.setText("Actualiza tu Disco");
        getContentPane().add(lblActualizarDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 204, -1));

        lblIDAct.setForeground(new java.awt.Color(255, 255, 255));
        lblIDAct.setText("ID");
        getContentPane().add(lblIDAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 48, -1));

        lblNombreAct.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreAct.setText("Nombre");
        getContentPane().add(lblNombreAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 48, -1));

        lblArtistaAct.setForeground(new java.awt.Color(255, 255, 255));
        lblArtistaAct.setText("Artista");
        getContentPane().add(lblArtistaAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 48, -1));

        lblAnoAct.setForeground(new java.awt.Color(255, 255, 255));
        lblAnoAct.setText("Año");
        getContentPane().add(lblAnoAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 48, -1));

        lblDuracionAct.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracionAct.setText("Duracion");
        getContentPane().add(lblDuracionAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        lblRankingAct.setForeground(new java.awt.Color(255, 255, 255));
        lblRankingAct.setText("Ranking");
        getContentPane().add(lblRankingAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 48, -1));

        lblGeneroAct.setForeground(new java.awt.Color(255, 255, 255));
        lblGeneroAct.setText("Genero");
        getContentPane().add(lblGeneroAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 48, -1));

        txtIdAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActActionPerformed(evt);
            }
        });
        txtIdAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdActKeyTyped(evt);
            }
        });
        getContentPane().add(txtIdAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 333, -1));

        txtNombreAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActActionPerformed(evt);
            }
        });
        txtNombreAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreActKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombreAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 333, -1));

        txtArtistaAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArtistaActKeyTyped(evt);
            }
        });
        getContentPane().add(txtArtistaAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 333, -1));

        txtAnoAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnoActKeyTyped(evt);
            }
        });
        getContentPane().add(txtAnoAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 333, -1));

        txtDuracionAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuracionActKeyTyped(evt);
            }
        });
        getContentPane().add(txtDuracionAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 333, -1));

        txtRankingAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRankingActKeyTyped(evt);
            }
        });
        getContentPane().add(txtRankingAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 333, -1));

        txtGeneroAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGeneroActKeyTyped(evt);
            }
        });
        getContentPane().add(txtGeneroAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 333, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disquera/imagenes/foto3.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActualizarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActualizarDiscoActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_botonCerrarActualizarDiscoActionPerformed

    private void txtIdActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActActionPerformed

    private void txtIdActKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdActKeyTyped
        // TODO add your handling code here:
         char caracterTeclado = evt.getKeyChar();
        
        if(!Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdActKeyTyped

    private void txtNombreActKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreActKeyTyped
        // TODO add your handling code here:
        char caracterTeclado = evt.getKeyChar();
        
        if(Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreActKeyTyped

    private void txtArtistaActKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArtistaActKeyTyped
        // TODO add your handling code here:
        char caracterTeclado = evt.getKeyChar();
        
        if(Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtArtistaActKeyTyped

    private void txtAnoActKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoActKeyTyped
        // TODO add your handling code here:
        char caracterTeclado = evt.getKeyChar();
        
        if(!Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtAnoActKeyTyped

    private void txtDuracionActKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuracionActKeyTyped
        // TODO add your handling code here:
        char caracterTeclado = evt.getKeyChar();
        
        if(!Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtDuracionActKeyTyped

    private void txtRankingActKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRankingActKeyTyped
        // TODO add your handling code here:
        char caracterTeclado = evt.getKeyChar();
        
        if(!Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtRankingActKeyTyped

    private void txtGeneroActKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeneroActKeyTyped
        // TODO add your handling code here:
        char caracterTeclado = evt.getKeyChar();
        
        if(Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtGeneroActKeyTyped

    private void botonActualizarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarDiscoActionPerformed
        try
        { 
            if (txtIdAct.getText().trim().isEmpty() || txtNombreAct.getText().trim().isEmpty() || txtArtistaAct.getText().trim().isEmpty() ||
            txtAnoAct.getText().trim().isEmpty() || txtDuracionAct.getText().trim().isEmpty() || txtRankingAct.getText().trim().isEmpty() ||
            txtGeneroAct.getText().trim().isEmpty()) 
            {
                JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos", "Error de Registro", JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            int Id;
            try 
            {
                Id = Integer.parseInt(txtIdAct.getText().trim());
            } 
            catch (NumberFormatException e) 
            {
                JOptionPane.showMessageDialog(this, "El ID debe ser numérico.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            String Nombre = txtNombreAct.getText();         
            
            String Artista = txtArtistaAct.getText();
            
            int Ano;
            try 
            {
                Ano = Integer.parseInt(txtAnoAct.getText().trim());
            } 
            catch (NumberFormatException e) 
            {
                JOptionPane.showMessageDialog(this, "El año debe ser numérico.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int Duracion;
            try 
            {
                Duracion = Integer.parseInt(txtDuracionAct.getText().trim());
            } 
            catch (NumberFormatException e) 
            {
                JOptionPane.showMessageDialog(this, "La duración debe ser numérica.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int Ranking;
            try 
            {
                Ranking = Integer.parseInt(txtRankingAct.getText().trim());
            }
            catch (NumberFormatException e) 
            {
                JOptionPane.showMessageDialog(this, "El ranking debe ser numérico.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            String Genero = txtGeneroAct.getText();

            Disco oDisco = new Disco(Id, Nombre, Artista, Ano, Duracion, Ranking, Genero);
            DiscoDAO can = new DiscoDAO();
            Disco buscado = can.buscarDisco(Id);
            
            if (buscado == null) 
            {
                JOptionPane.showMessageDialog(this, "No existe un disco con ese ID.", "No encontrado", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            boolean ok = can.actualizarDisco(oDisco);
            if(ok)
            {
                JOptionPane.showMessageDialog(this, "Operación realizada con éxito");
            } 
            else 
            {
                JOptionPane.showMessageDialog(this, "No se actualizó ninguna fila");
            }
            
            super.dispose();
        }
        
        catch(DiscoException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
        }
        catch(NumberFormatException nex)
        {
            JOptionPane.showMessageDialog(this, "Debe Ingresar Los Datos", "Error de Registro", JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error Inesperado: " + e.getMessage());
        }
        
    }//GEN-LAST:event_botonActualizarDiscoActionPerformed

    private void txtNombreActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmActualizarDisco dialog = new FrmActualizarDisco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarDisco;
    private javax.swing.JButton botonCerrarActualizarDisco;
    private javax.swing.JLabel lblActualizarDisco;
    private javax.swing.JLabel lblAnoAct;
    private javax.swing.JLabel lblArtistaAct;
    private javax.swing.JLabel lblDuracionAct;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGeneroAct;
    private javax.swing.JLabel lblIDAct;
    private javax.swing.JLabel lblNombreAct;
    private javax.swing.JLabel lblRankingAct;
    private javax.swing.JTextField txtAnoAct;
    private javax.swing.JTextField txtArtistaAct;
    private javax.swing.JTextField txtDuracionAct;
    private javax.swing.JTextField txtGeneroAct;
    private javax.swing.JTextField txtIdAct;
    private javax.swing.JTextField txtNombreAct;
    private javax.swing.JTextField txtRankingAct;
    // End of variables declaration//GEN-END:variables
}
