/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package disquera.gui;

import javax.swing.JOptionPane;
import disquera.exception.DiscoException;
import disquera.beans.Disco;
import disquera.datos.DiscoDAO;

/**
 *
 * @author Sebastian
 */
public class FrmBuscarDisco extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBuscarDisco.class.getName());

    /**
     * Creates new form FrmBuscarDisco
     */
    public FrmBuscarDisco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBuscarDisco = new javax.swing.JButton();
        lblBuscardisco = new javax.swing.JLabel();
        botonCerrarBuscar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblRanking = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtArtista = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtRanking = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();
        barraDeMenuBuscarDisco = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscador de Disco ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonBuscarDisco.setText("Buscar");
        botonBuscarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarDiscoActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscarDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        lblBuscardisco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBuscardisco.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscardisco.setText("                         Busca un Disco");
        getContentPane().add(lblBuscardisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 420, -1));

        botonCerrarBuscar.setText("Cerrar");
        botonCerrarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerrarBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("ID");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 37, -1));

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 54, -1));

        lblArtista.setForeground(new java.awt.Color(255, 255, 255));
        lblArtista.setText("Artista");
        getContentPane().add(lblArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 54, -1));

        lblAno.setForeground(new java.awt.Color(255, 255, 255));
        lblAno.setText("Año");
        getContentPane().add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 54, -1));

        lblDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracion.setText("Duracion");
        getContentPane().add(lblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 54, -1));

        lblRanking.setForeground(new java.awt.Color(255, 255, 255));
        lblRanking.setText("Ranking");
        getContentPane().add(lblRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 54, -1));

        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("Genero");
        getContentPane().add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 54, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 394, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 394, -1));
        getContentPane().add(txtArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 394, -1));
        getContentPane().add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 394, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 394, -1));
        getContentPane().add(txtRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 394, -1));
        getContentPane().add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 394, -1));

        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disquera/imagenes/foto6.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, 0, 1060, 590));
        setJMenuBar(barraDeMenuBuscarDisco);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarBuscarActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_botonCerrarBuscarActionPerformed

    private void botonBuscarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarDiscoActionPerformed
        // TODO add your handling code here:
        try 
        {
            int id = Integer.parseInt(txtId.getText()); 
            DiscoDAO oDiscoDAO = new DiscoDAO();
            Disco disco = oDiscoDAO.buscarDisco(id);
        
            if(disco == null)
            {
                JOptionPane.showMessageDialog(this, "No se encontró un disco con ese ID");
                return;
            }

            txtId.setText(String.valueOf(disco.getID()));
            txtNombre.setText(disco.getNombre());
            txtArtista.setText(disco.getArtista());
            txtAno.setText(String.valueOf(disco.getAno()));      
            txtDuracion.setText(String.valueOf(disco.getDuracion()));
            txtRanking.setText(String.valueOf(disco.getRanking()));
            txtGenero.setText(disco.getGenero());     
        
        } 
        
        catch(NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número", "Error", JOptionPane.ERROR_MESSAGE);
        }

        catch (Exception ex) 
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_botonBuscarDiscoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmBuscarDisco dialog = new FrmBuscarDisco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenuBuscarDisco;
    private javax.swing.JButton botonBuscarDisco;
    private javax.swing.JButton botonCerrarBuscar;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblBuscardisco;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRanking;
    // End of variables declaration//GEN-END:variables
}
