/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package disquera.gui;

import javax.swing.JOptionPane;
import disquera.exception.CancionException;
import disquera.beans.Cancion;
import disquera.datos.CancionDAO;

/**
 *
 * @author Sebastian
 */
public class FrmBuscarCancion extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBuscarCancion.class.getName());

    /**
     * Creates new form FrmBuscarCancion
     */
    public FrmBuscarCancion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscarcacion = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        txtDuracion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscador de Canciones ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscarcacion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblBuscarcacion.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscarcacion.setText("Busca una Cancion");
        getContentPane().add(lblBuscarcacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 310, -1));

        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 80, 30));

        botonBuscar.setText("Buscar");
        botonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 70, 30));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 350, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 350, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 350, -1));

        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("ID");
        lblId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 65, -1));

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        lblNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 65, -1));

        lblDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracion.setText("Duracion");
        lblDuracion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 65, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disquera/imagenes/foto5.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 0, 860, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        
    try 
    {
        if (txtId.getText().trim().isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int id;
        try 
        {
            id = Integer.parseInt(txtId.getText().trim());
        }
        catch (NumberFormatException e) 
            
        {
            JOptionPane.showMessageDialog(this, "El ID debe ser numérico.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        CancionDAO oCancionDAO = new CancionDAO();
        Cancion cancion = oCancionDAO.buscarCancion(id);
        if (cancion == null) 
        {
            JOptionPane.showMessageDialog(this, "No se encontró ninguna canción con ese ID.", "No encontrado", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        txtId.setText(String.valueOf(cancion.getID()));
        txtNombre.setText(cancion.getNombre());
        txtDuracion.setText(String.valueOf(cancion.getDuracion()));

    } 
    catch (Exception ex) 
    {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
    }
    
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmBuscarCancion dialog = new FrmBuscarCancion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel lblBuscarcacion;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
