/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package disquera.gui;

import javax.swing.JOptionPane;
import disquera.beans.Cancion;
import disquera.datos.CancionDAO;
import disquera.exception.CancionException;


/**
 *
 * @author Sebastian
 */
public class FrmEliminarCancion extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEliminarCancion.class.getName());

    /**
     * Creates new form FrmEliminarCancion
     */
    public FrmEliminarCancion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEliminarCancion = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        botonCerar = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminacion de Canciones ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEliminarCancion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEliminarCancion.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminarCancion.setText("                                  Eliminar Cancion");
        getContentPane().add(lblEliminarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 83, 474, 30));

        botonEliminar.setText("Eliminar");
        botonEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 566, 91, -1));

        botonCerar.setText("Cerrar");
        botonCerar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 566, 101, -1));

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 191, 61, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 253, 61, -1));

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracion.setText("Duracion");
        getContentPane().add(lblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 308, 61, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 191, 214, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 253, 214, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 308, 214, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disquera/imagenes/foto8.jpeg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -14, 850, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        
        try
        {
            if (txtID.getText().trim().isEmpty()) 
            {
                JOptionPane.showMessageDialog(this, "Debe ingresar un ID.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int Id;
            try 
            {
                Id = Integer.parseInt(txtID.getText().trim());
            } 
            catch (NumberFormatException e) 
            {
                JOptionPane.showMessageDialog(this, "El ID debe ser numérico.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            int conformacion = JOptionPane.showConfirmDialog(this, "¿Desea Eliminar la Cancion?");

            if(conformacion == 0)
            {
                int ID = Integer.parseInt(txtID.getText());
                CancionDAO oCancionDAO = new CancionDAO();
                boolean seElimino = oCancionDAO.eliminarCancion(ID);
                if(seElimino)
                {
                    JOptionPane.showMessageDialog(this, "La canción se eliminó Correctamente", "Eliminación Correcta", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Cancion no Eliminada", "Error de Eliminación", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Eliminación", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonCerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerarActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_botonCerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmEliminarCancion dialog = new FrmEliminarCancion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblEliminarCancion;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
