/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package disquera.gui;

import javax.swing.JOptionPane;
import disquera.beans.Disco;
import disquera.datos.DiscoDAO;
import disquera.exception.DiscoException;

/**
 *
 * @author Sebastian
 */
public class FrmEliminarDisco extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEliminarDisco.class.getName());

    /**
     * Creates new form FrmEliminarDisco
     */
    public FrmEliminarDisco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonEliminarDisco = new javax.swing.JButton();
        botonCerrarDiscoEliminar = new javax.swing.JButton();
        lblEliminar = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblRanking = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtArtista = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtRanking = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminacion de Disco");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonEliminarDisco.setBackground(new java.awt.Color(255, 0, 0));
        botonEliminarDisco.setText("Eliminar");
        botonEliminarDisco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEliminarDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarDiscoActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminarDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 100, 30));

        botonCerrarDiscoEliminar.setBackground(new java.awt.Color(0, 153, 51));
        botonCerrarDiscoEliminar.setText("Cerrar");
        botonCerrarDiscoEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrarDiscoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarDiscoEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerrarDiscoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 100, 30));

        lblEliminar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setText("Elimina un Disco");
        getContentPane().add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 280, -1));

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("ID");
        lblId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 80, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        lblNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 80, -1));

        lblArtista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblArtista.setForeground(new java.awt.Color(255, 255, 255));
        lblArtista.setText("Artista");
        lblArtista.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 80, -1));

        lblAno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAno.setForeground(new java.awt.Color(255, 255, 255));
        lblAno.setText("Año");
        lblAno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 80, -1));

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDuracion.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracion.setText("Duracion");
        lblDuracion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 80, -1));

        lblRanking.setBackground(new java.awt.Color(255, 255, 255));
        lblRanking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRanking.setForeground(new java.awt.Color(255, 255, 255));
        lblRanking.setText("Ranking");
        lblRanking.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 80, -1));

        lblGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("Genero");
        lblGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 80, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 229, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 229, -1));
        getContentPane().add(txtArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 229, -1));
        getContentPane().add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 229, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 229, -1));
        getContentPane().add(txtRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 229, -1));
        getContentPane().add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 229, -1));

        lblFondo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFondo.setForeground(new java.awt.Color(255, 255, 255));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disquera/imagenes/foto7.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, 0, 1040, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarDiscoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarDiscoEliminarActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_botonCerrarDiscoEliminarActionPerformed

    private void botonEliminarDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarDiscoActionPerformed
        // TODO add your handling code here:
        try
        {
            if (txtId.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Debe ingresar un ID.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int Id;
            try
            {
                Id = Integer.parseInt(txtId.getText().trim());
            }
            
            catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "El ID debe ser numérico.", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            
            int conformacion = JOptionPane.showConfirmDialog(this, "¿Desea Eliminar este Disco?", "Confirmar", JOptionPane.YES_NO_OPTION);

            if(conformacion == JOptionPane.YES_OPTION)
            {
                DiscoDAO oDiscoDAO = new DiscoDAO();
                boolean seElimino = oDiscoDAO.eliminarDisco(Id);
                if(seElimino)
                {
                    JOptionPane.showMessageDialog(this, "El Disco se eliminó Correctamente", "Eliminación Correcta", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Disco no Eliminado", "Error de Eliminación", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Eliminación", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_botonEliminarDiscoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmEliminarDisco dialog = new FrmEliminarDisco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarDiscoEliminar;
    private javax.swing.JButton botonEliminarDisco;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRanking;
    // End of variables declaration//GEN-END:variables
}
