/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package disquera.gui;

import disquera.exception.DiscoException;
import disquera.beans.Disco;
import javax.swing.JOptionPane;
import disquera.datos.DiscoDAO;

/**
 *
 * @author Sebastian
 */
public class FrmIngresoDisco extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmIngresoDisco.class.getName());

    /**
     * Creates new form FrmIngresoDisco
     */
    public FrmIngresoDisco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscar = new javax.swing.JLabel();
        txtIdDisco = new javax.swing.JTextField();
        botonOkIngresoDisco = new javax.swing.JButton();
        botonIngresarCerrar = new javax.swing.JButton();
        txtNombreDisco = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblNombreDisco = new javax.swing.JLabel();
        lblArtistaDisco = new javax.swing.JLabel();
        lblAnoDisco = new javax.swing.JLabel();
        lblDuracionDisco = new javax.swing.JLabel();
        lblRankingDisco = new javax.swing.JLabel();
        lblGeneroDisco = new javax.swing.JLabel();
        txtArtistaDisco = new javax.swing.JTextField();
        txtAnoDisco = new javax.swing.JTextField();
        txtDuracionDisco = new javax.swing.JTextField();
        txtRankingDisco = new javax.swing.JTextField();
        txtGeneroDisco = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar disco");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Ingresa un Nuevo Disco");
        getContentPane().add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        txtIdDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdDiscoActionPerformed(evt);
            }
        });
        txtIdDisco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdDiscoKeyTyped(evt);
            }
        });
        getContentPane().add(txtIdDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 267, -1));

        botonOkIngresoDisco.setBackground(new java.awt.Color(51, 204, 0));
        botonOkIngresoDisco.setText("OK");
        botonOkIngresoDisco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOkIngresoDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOkIngresoDiscoActionPerformed(evt);
            }
        });
        getContentPane().add(botonOkIngresoDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 90, 30));

        botonIngresarCerrar.setBackground(new java.awt.Color(255, 0, 51));
        botonIngresarCerrar.setText("Cerrar");
        botonIngresarCerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonIngresarCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonIngresarCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 90, 30));

        txtNombreDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDiscoActionPerformed(evt);
            }
        });
        txtNombreDisco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreDiscoKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombreDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 267, -1));

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("ID");
        lblId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, -1));

        lblNombreDisco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreDisco.setText("Nombre");
        lblNombreDisco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblNombreDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        lblArtistaDisco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblArtistaDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblArtistaDisco.setText("Artista");
        lblArtistaDisco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblArtistaDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 60, -1));

        lblAnoDisco.setBackground(new java.awt.Color(0, 0, 0));
        lblAnoDisco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnoDisco.setText("Año");
        lblAnoDisco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblAnoDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 60, -1));

        lblDuracionDisco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDuracionDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracionDisco.setText("Duración");
        lblDuracionDisco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblDuracionDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 70, -1));

        lblRankingDisco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRankingDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblRankingDisco.setText("Ranking");
        lblRankingDisco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblRankingDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        lblGeneroDisco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGeneroDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblGeneroDisco.setText("Genero");
        lblGeneroDisco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblGeneroDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 60, -1));

        txtArtistaDisco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArtistaDiscoKeyTyped(evt);
            }
        });
        getContentPane().add(txtArtistaDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 267, -1));

        txtAnoDisco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAnoDiscoKeyTyped(evt);
            }
        });
        getContentPane().add(txtAnoDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 267, -1));

        txtDuracionDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionDiscoActionPerformed(evt);
            }
        });
        txtDuracionDisco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuracionDiscoKeyTyped(evt);
            }
        });
        getContentPane().add(txtDuracionDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 267, -1));

        txtRankingDisco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRankingDiscoKeyTyped(evt);
            }
        });
        getContentPane().add(txtRankingDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 267, -1));

        txtGeneroDisco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGeneroDiscoKeyTyped(evt);
            }
        });
        getContentPane().add(txtGeneroDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 267, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disquera/imagenes/foto12.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 1000, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDiscoActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtIdDiscoActionPerformed

    private void botonIngresarCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarCerrarActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_botonIngresarCerrarActionPerformed

    private void botonOkIngresoDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOkIngresoDiscoActionPerformed
        // TODO add your handling code here:
        try
        {
            if (txtIdDisco.getText().trim().isEmpty() || txtNombreDisco.getText().trim().isEmpty() || txtArtistaDisco.getText().trim().isEmpty() ||
            txtAnoDisco.getText().trim().isEmpty() || txtDuracionDisco.getText().trim().isEmpty() ||
            txtRankingDisco.getText().trim().isEmpty() || txtGeneroDisco.getText().trim().isEmpty()) 
            {
                JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos", "Error de Registro", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int Id, Ano, Duracion, Ranking;
            String Nombre = txtNombreDisco.getText().trim();
            String Artista = txtArtistaDisco.getText().trim();
            String Genero = txtGeneroDisco.getText().trim();
            
            try 
            {
                Id = Integer.parseInt(txtIdDisco.getText().trim());
                Ano = Integer.parseInt(txtAnoDisco.getText().trim());
                Duracion = Integer.parseInt(txtDuracionDisco.getText().trim());
                Ranking = Integer.parseInt(txtRankingDisco.getText().trim());
            } 
            catch(NumberFormatException e) 
            {
                JOptionPane.showMessageDialog(this, "Los campos numéricos deben ser válidos", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            Disco oDisco = new Disco(Id, Nombre, Artista, Ano, Duracion, Ranking, Genero);
            DiscoDAO oDiscoDAO = new DiscoDAO();
            oDiscoDAO.agregarDisco(oDisco);
            JOptionPane.showMessageDialog(this, "Operación realizada con éxito", "Información", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        catch (DiscoException dex) 
        {
             JOptionPane.showMessageDialog(this, dex.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
        } 
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
        }
        
         
         
    }//GEN-LAST:event_botonOkIngresoDiscoActionPerformed

    private void txtDuracionDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionDiscoActionPerformed

    private void txtIdDiscoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdDiscoKeyTyped
        // TODO add your handling code here:
          char caracterTeclado = evt.getKeyChar();
        
        if(!Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdDiscoKeyTyped

    private void txtNombreDiscoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDiscoKeyTyped
        // TODO add your handling code here:
          char caracterTeclado = evt.getKeyChar();
        
        if(Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreDiscoKeyTyped

    private void txtArtistaDiscoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArtistaDiscoKeyTyped
        // TODO add your handling code here:
          char caracterTeclado = evt.getKeyChar();
        
        if(Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtArtistaDiscoKeyTyped

    private void txtAnoDiscoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAnoDiscoKeyTyped
        // TODO add your handling code here:
          char caracterTeclado = evt.getKeyChar();
        
        if(!Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtAnoDiscoKeyTyped

    private void txtDuracionDiscoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuracionDiscoKeyTyped
        // TODO add your handling code here:
          char caracterTeclado = evt.getKeyChar();
        
        if(!Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtDuracionDiscoKeyTyped

    private void txtRankingDiscoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRankingDiscoKeyTyped
        // TODO add your handling code here:
          char caracterTeclado = evt.getKeyChar();
        
        if(!Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtRankingDiscoKeyTyped

    private void txtGeneroDiscoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeneroDiscoKeyTyped
        // TODO add your handling code here:
          char caracterTeclado = evt.getKeyChar();
        
        if(Character.isDigit(caracterTeclado))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtGeneroDiscoKeyTyped

    private void txtNombreDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDiscoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDiscoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmIngresoDisco dialog = new FrmIngresoDisco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresarCerrar;
    private javax.swing.JButton botonOkIngresoDisco;
    private javax.swing.JLabel lblAnoDisco;
    private javax.swing.JLabel lblArtistaDisco;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDuracionDisco;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGeneroDisco;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombreDisco;
    private javax.swing.JLabel lblRankingDisco;
    private javax.swing.JTextField txtAnoDisco;
    private javax.swing.JTextField txtArtistaDisco;
    private javax.swing.JTextField txtDuracionDisco;
    private javax.swing.JTextField txtGeneroDisco;
    private javax.swing.JTextField txtIdDisco;
    private javax.swing.JTextField txtNombreDisco;
    private javax.swing.JTextField txtRankingDisco;
    // End of variables declaration//GEN-END:variables
}
