/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package disquera.gui;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

import disquera.beans.Disco;
import disquera.exception.DiscoException;
import disquera.datos.DiscoDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian Cornejo
 */
public class FrmListarDisco extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmListarDisco.class.getName());

    /**
     * Creates new form FrmListarDisco
     */
    public FrmListarDisco(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        setComponents();
    }
    
     public void setComponents() 
     {
        this.listarDisco();
        super.setLocationRelativeTo(this);
    }
    
    public void listarDisco() 
    {
        try
        {
            String[] cabecera = { "ID", "Nombre", "Artista", "Anio", "Duración", "Ranking", "Genero"};
            DefaultTableModel modelo = new DefaultTableModel(cabecera, 0)
            {
                public boolean isCellEditable(int row, int column) 
                {
                    return false; // evita que las celdas sean editables
                }
            };
            

            DiscoDAO oDiscoDAO = new DiscoDAO();
            List<Disco> lstDisco = oDiscoDAO.listarDisco();

            if(lstDisco.isEmpty()) 
            {
                JOptionPane.showMessageDialog(this, "No hay discos registrados.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
            
            for (Disco disco : lstDisco)
            {
                Object[] fila = 
                {
                    disco.getID(),
                    disco.getNombre(),
                    disco.getArtista(),
                    disco.getAno(),
                    disco.getDuracion(),
                    disco.getRanking(),
                    disco.getGenero()
                };

                modelo.addRow(fila);
            }
            
            tbDisco.setModel(modelo);
            
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
        }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonListaDiscoCerrar = new javax.swing.JButton();
        lblLista = new javax.swing.JLabel();
        spScroll = new javax.swing.JScrollPane();
        tbDisco = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista  de Discos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonListaDiscoCerrar.setBackground(new java.awt.Color(204, 0, 0));
        botonListaDiscoCerrar.setText("Cerrar");
        botonListaDiscoCerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonListaDiscoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaDiscoCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonListaDiscoCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, 110, 30));

        lblLista.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblLista.setForeground(new java.awt.Color(255, 255, 255));
        lblLista.setText("Lista de tus Discos");
        lblLista.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 303, 60));
        lblLista.getAccessibleContext().setAccessibleName("\t\t\tLista de tus Discos");

        tbDisco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        spScroll.setViewportView(tbDisco);

        getContentPane().add(spScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 440, 440));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disquera/imagenes/foto11.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, 0, 1170, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListaDiscoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaDiscoCerrarActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_botonListaDiscoCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmListarDisco dialog = new FrmListarDisco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonListaDiscoCerrar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLista;
    private javax.swing.JScrollPane spScroll;
    private javax.swing.JTable tbDisco;
    // End of variables declaration//GEN-END:variables
}
