/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package disquera.gui;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

import disquera.beans.Cancion;
import disquera.exception.CancionException;
import disquera.datos.CancionDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian Cornejo
 */
public class FrmListarCancion extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmListarCancion.class.getName());

    /**
     * Creates new form FrmListarCancion
     */
    public FrmListarCancion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setComponents();
    }
    
    public void setComponents() {
        this.listarCanciones();
        super.setLocationRelativeTo(this);
    }
    
    public void listarCanciones() 
    {
        try
        {
            String[] cabecera = { "ID", "Nombre", "Duración" };
            DefaultTableModel modelo = new DefaultTableModel(cabecera, 0)
            {
            public boolean isCellEditable(int row, int column) 
                {
                    return false;
                }
            };

            CancionDAO oCancionDAO = new CancionDAO();
            List<Cancion> lstCanciones = oCancionDAO.listarCancion();
            
            if (lstCanciones.isEmpty()) 
            {
                JOptionPane.showMessageDialog(this, "No hay canciones registradas.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
            
            for (Cancion cancion : lstCanciones)
            {
                Object[] fila = 
                {
                    cancion.getID(),
                    cancion.getNombre(),
                    cancion.getDuracion()
                };

                modelo.addRow(fila);
            }
            
            tbClientes.setModel(modelo);
            
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de Registro", JOptionPane.WARNING_MESSAGE);
        }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListarCancion = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        spScroll = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de canciones ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblListarCancion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblListarCancion.setForeground(new java.awt.Color(255, 255, 255));
        lblListarCancion.setText("Lista de tus Canciones");
        getContentPane().add(lblListarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 364, 31));

        botonCerrar.setBackground(new java.awt.Color(255, 204, 51));
        botonCerrar.setText("Cerrar");
        botonCerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 100, 40));

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        spScroll.setViewportView(tbClientes);

        getContentPane().add(spScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 572, 420));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disquera/imagenes/foto10.jpeg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 720, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FrmListarCancion dialog = new FrmListarCancion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblListarCancion;
    private javax.swing.JScrollPane spScroll;
    private javax.swing.JTable tbClientes;
    // End of variables declaration//GEN-END:variables
}
